name: Semgrep SAST Scan

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          paths: frontend backend
